import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
const story = "http://127.0.0.1:6006/iframe.html?id=workroom-board--default&viewMode=story";
test.beforeEach(async ({ page }) => { await page.goto(story); await expect(page.locator("#work-item-1")).toBeVisible(); });

test("search and status filters compose, show counts, and clear without changing the archive", async ({ page }) => {
  await page.getByRole("button", { name: "Search board", exact: true }).click();
  const search = page.getByRole("searchbox", { name: "Search work items" });
  await expect(search).toBeFocused();
  await search.fill("Review");
  await expect(page.locator('[id^="work-item-"]')).toHaveCount(1);
  await expect(page.getByRole("status").filter({ hasText: "1 matching tasks" })).toBeVisible();
  await page.getByRole("button", { name: "Filter by status", exact: true }).click();
  await page.getByRole("menuitemcheckbox", { name: "Blocked", exact: true }).click();
  await expect(page.getByRole("menuitemcheckbox", { name: "Blocked", exact: true })).toBeChecked();
  await page.keyboard.press("Escape");
  await expect(page.locator('[id^="work-item-"]')).toHaveCount(0);
  await expect(page.getByRole("status").filter({ hasText: "0 matching tasks" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Archive (0)", exact: true })).toHaveAttribute("aria-expanded", "false");
  await page.getByRole("button", { name: "Clear search and filters", exact: true }).click();
  await expect(page.locator('[id^="work-item-"]')).toHaveCount(6);
  await search.press("Escape");
  await expect(search).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Search board", exact: true })).toBeFocused();
});
test("inline creation validates, assigns the column, focuses the card, and cancels without creating", async ({ page }) => {
  await page.getByRole("button", { name: "New task in Blocked", exact: true }).click();
  const form = page.getByRole("form", { name: "New item in Blocked" });
  const title = form.getByRole("textbox", { name: "Task title" });
  await expect(title).toBeFocused();
  await title.fill("   ");
  await form.getByRole("button", { name: "Add task", exact: true }).click();
  await expect(form.getByRole("alert")).toHaveText("Enter a task title.");
  await title.fill("Follow up");
  await title.press("Enter");
  const task = page.getByRole("region", { name: "Blocked", exact: true }).getByRole("button", { name: "Follow up", exact: true });
  await expect(task).toBeFocused();
  await expect(page.getByRole("region", { name: "Blocked", exact: true }).locator('[id^="work-item-"]')).toHaveCount(2);
  await page.getByRole("button", { name: "New", exact: true }).click();
  await page.getByRole("textbox", { name: "Task title" }).fill("Discard this");
  await page.keyboard.press("Escape");
  await expect(page.getByRole("textbox", { name: "Task title" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "New task in Backlog", exact: true })).toBeFocused();
  await expect(page.getByRole("button", { name: "Discard this", exact: true })).toHaveCount(0);
});
test("new tasks hidden by a filter are explained rather than silently lost", async ({ page }) => {
  await page.getByRole("button", { name: "Search board", exact: true }).click();
  await page.getByRole("searchbox", { name: "Search work items" }).fill("unmatched");
  await page.getByRole("button", { name: "New task in Completed", exact: true }).click();
  await page.getByRole("textbox", { name: "Task title" }).fill("Delivered");
  await page.getByRole("button", { name: "Add task", exact: true }).click();
  await expect(page.getByRole("status").filter({ hasText: "Task added. Clear search and filters to see it." })).toBeVisible();
  await expect(page.getByRole("button", { name: "New task in Completed", exact: true })).toBeFocused();
  await page.getByRole("button", { name: "Clear search and filters", exact: true }).click();
  await expect(page.getByRole("region", { name: "Completed", exact: true }).getByRole("button", { name: "Delivered", exact: true })).toBeVisible();
});
test("sorting is reversible and never pretends to support manual reordering while sorted", async ({ page }) => {
  const list = page.getByRole("list", { name: "Backlog items" }).locator('[id^="work-item-"]');
  await page.getByRole("button", { name: "Sort work items", exact: true }).click();
  await page.getByRole("menuitemradio", { name: "Title: Z to A", exact: true }).click();
  await expect(list).toHaveText(["Review requirements", "Plan next release"]);
  const task = page.locator("#work-item-1");
  await task.focus();
  await page.keyboard.press("Space");
  await expect(task).toHaveAttribute("aria-pressed", "true");
  await page.keyboard.press("Alt+ArrowUp");
  await expect(page.getByRole("status").filter({ hasText: "Choose Manual order in Sort to rearrange tasks." })).toBeVisible();
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "Sort work items", exact: true }).click();
  await page.getByRole("menuitemradio", { name: "Manual order", exact: true }).click();
  await expect(list).toHaveText(["Plan next release", "Review requirements"]);
});
test("a filtered-out move keeps keyboard focus on the board", async ({ page }) => {
  await page.getByRole("button", { name: "Search board", exact: true }).click();
  await page.getByRole("searchbox", { name: "Search work items" }).fill("Backlog");
  const task = page.locator("#work-item-1");
  await task.focus();
  await page.keyboard.press("Space");
  await expect(task).toHaveAttribute("aria-pressed", "true");
  await page.keyboard.press("ArrowRight");
  await expect(page.getByRole("region", { name: "In progress", exact: true })).toHaveAttribute("data-over", "true");
  await page.keyboard.press("Space");
  await expect(task).toHaveCount(0);
  await expect(page.locator("#board-items")).toBeFocused();
});
test("sorted tasks can still move between columns with the keyboard", async ({ page }) => {
  await page.getByRole("button", { name: "Sort work items", exact: true }).click();
  await page.getByRole("menuitemradio", { name: "Title: Z to A", exact: true }).click();
  const task = page.locator("#work-item-1");
  await task.focus();
  await page.keyboard.press("Space");
  await expect(task).toHaveAttribute("aria-pressed", "true");
  await page.keyboard.press("ArrowRight");
  const lane = page.getByRole("region", { name: "In progress", exact: true });
  await expect(lane).toHaveAttribute("data-over", "true");
  await page.keyboard.press("Space");
  await expect(lane.locator("#work-item-1")).toBeFocused();
  await expect(lane.locator('[id^="work-item-"]')).toHaveText(["Write tests", "Plan next release", "Build components"]);
});
test("filter menu and inline composer retain native accessible semantics", async ({ page }) => {
  await page.getByRole("button", { name: "Filter by status", exact: true }).click();
  expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "New task in Backlog", exact: true }).click();
  expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
});
