import { test, expect, workItemTotal } from "./project-fixture";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import AxeBuilder from "@axe-core/playwright";

test("creating a real project from the menu persists across server restarts and preserves Tasks", async ({ page, projectServer: server }) => {
  await page.goto(`${server.url}/bohemia/tasks`);
  await page.getByRole("button", { name: "Switch project, Bohemia" }).click();
  await page.getByRole("menuitem", { name: "Create project...", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Create project", exact: true });
  const name = dialog.getByRole("textbox", { name: /^Project name/ });
  await expect(name).toBeFocused();
  await name.fill("Recipe development");
  await dialog.getByRole("textbox", { name: /^Spool folder/ }).fill(server.bookCook);
  expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
  await dialog.getByRole("button", { name: "Create project", exact: true }).click();
  await expect(page.getByRole("button", { name: "Switch project, Recipe development" })).toBeVisible();
  await expect(page.locator("[data-work-item-id]")).toHaveCount(3);
  await expect(page).toHaveURL(/\/[a-f0-9-]+\/tasks$/);
  const target = page.url();
  const saved = JSON.parse(await readFile(server.registry, "utf8"));
  expect(saved.projects.map((project: { name: string }) => project.name)).toEqual(["Bohemia", "Recipe development"]);
  await server.restart(); await page.goto(target);
  await expect(page.getByRole("button", { name: "Switch project, Recipe development" })).toBeVisible();
  await expect(page.locator("[data-work-item-id]")).toHaveCount(3);
  await page.getByRole("link", { name: "Home", exact: true }).click(); await expect(workItemTotal(page)).toHaveText("3 work items");
});
test("creation reports invalid folders and duplicates without losing entered values or existing settings", async ({ page, projectServer: server }) => {
  const before = await readFile(server.registry, "utf8");
  await page.goto(`${server.url}/bohemia`);
  const trigger = page.getByRole("button", { name: "Switch project, Bohemia" });
  await trigger.click(); await page.getByRole("menuitem", { name: "Create project...", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Create project", exact: true });
  const name = dialog.getByRole("textbox", { name: /^Project name/ }), folder = dialog.getByRole("textbox", { name: /^Spool folder/ });
  const submit = dialog.getByRole("button", { name: "Create project", exact: true });
  await name.fill("Different"); await folder.fill(join(server.root, "missing")); await submit.click();
  await expect(dialog.getByRole("alert")).toContainText("must contain queues");
  await expect(name).toHaveValue("Different");
  await folder.fill(server.bohemia); await submit.click();
  await expect(dialog.getByRole("alert")).toContainText("already connected");
  await name.fill("Bohemia"); await folder.fill(server.bookCook); await submit.click();
  await expect(dialog.getByRole("alert")).toContainText("name already exists");
  expect(await readFile(server.registry, "utf8")).toBe(before);
  await dialog.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(trigger).toBeFocused();
});
test("empty installations configure their first project without a hardcoded default", async ({ page, projectServer: server }) => {
  await writeFile(server.registry, JSON.stringify({ version: 1, projects: [] }));
  await page.goto(server.url);
  await expect(page.getByRole("heading", { name: "Projects", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Create project", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Create project", exact: true });
  await dialog.getByRole("textbox", { name: /^Project name/ }).fill("My own project");
  await dialog.getByRole("textbox", { name: /^Spool folder/ }).fill(server.empty);
  await dialog.getByRole("button", { name: "Create project", exact: true }).click();
  await expect(page.getByRole("button", { name: "Switch project, My own project" })).toBeVisible();
  await expect(workItemTotal(page)).toHaveText("0 work items");
  const target = page.url(); await page.goto(server.url); await expect(page).toHaveURL(target);
});
test("mobile menu opens the same accessible dialog and returns focus to its switcher", async ({ page, projectServer: server }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto(server.url);
  await page.getByRole("button", { name: "Open sidebar", exact: true }).click();
  const trigger = page.getByRole("button", { name: "Switch project, Bohemia" });
  await trigger.click(); await page.getByRole("menuitem", { name: "Create project...", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Create project", exact: true });
  await expect(dialog.getByRole("textbox", { name: /^Project name/ })).toBeFocused();
  await page.keyboard.press("Escape"); await expect(dialog).toBeHidden(); await expect(trigger).toBeFocused();
});
test("project writes reject cross-origin and invalid requests without changing task or registry files", async ({ request, projectServer: server }) => {
  const before = await readFile(server.registry, "utf8");
  const task = join(server.bohemia, "queues", "completed", "A-1.json"), original = await readFile(task, "utf8");
  const data = { name: "Rejected", root: server.bookCook };
  expect((await request.post(`${server.url}/api/projects`, { data, headers: { Origin: "http://other.example" } })).status()).toBe(403);
  expect((await request.post(`${server.url}/api/projects`, { data: "{broken", headers: { Origin: server.url, "Content-Type": "application/json" } })).status()).toBe(400);
  expect((await request.post(`${server.url}/api/projects`, { data: "text", headers: { Origin: server.url, "Content-Type": "text/plain" } })).status()).toBe(415);
  expect((await request.post(`${server.url}/api/projects`, { data: {}, headers: { Origin: server.url } })).status()).toBe(400);
  expect(await readFile(server.registry, "utf8")).toBe(before); expect(await readFile(task, "utf8")).toBe(original);
});
test("Spool folder picker uses the selected absolute path when saving a project", async ({ page, projectServer: server }) => {
  await page.route("**/api/file-picker?kind=folder", (route) => route.fulfill({ json: { path: server.bookCook } }));
  await page.goto(server.url);
  await page.getByRole("button", { name: "Switch project, Bohemia" }).click();
  await page.getByRole("menuitem", { name: "Create project...", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Create project", exact: true });
  await dialog.getByRole("textbox", { name: /^Project name/ }).fill("Picked project");
  await dialog.getByRole("button", { name: "Browse for Spool folder", exact: true }).click();
  await expect(dialog.getByRole("textbox", { name: /^Spool folder/ })).toHaveValue(server.bookCook);
  await dialog.getByRole("button", { name: "Create project", exact: true }).click();
  await expect(page.getByRole("button", { name: "Switch project, Picked project" })).toBeVisible();
  const saved = JSON.parse(await readFile(server.registry, "utf8"));
  expect(saved.projects.at(-1).name).toBe("Picked project");
});
