import { test, expect } from "./project-fixture";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

test("isolated runner editor creates and persists a runnable definition, rejects stale and cross-origin writes", async ({ page, projectServer: server }) => {
  test.setTimeout(90000);
  const home = join(server.root, "runner-service"), config = join(home, "spool-runners.json");
  await mkdir(join(home, "bridge"), { recursive: true });
  const cli = pathToFileURL(resolve("..", "spool-runners", "bridge", "workflow-cli.mjs")).href;
  const snapshot = pathToFileURL(resolve("..", "spool-runners", "bridge", "runner-snapshot.mjs")).href;
  await writeFile(join(home, "bridge", "workflow-cli.mjs"), `import ${JSON.stringify(cli)};`);
  await writeFile(join(home, "bridge", "runner-snapshot.mjs"), `import { readFileSync } from "node:fs";
    import { runnerSnapshot } from ${JSON.stringify(snapshot)};
    console.log(JSON.stringify(await runnerSnapshot(JSON.parse(readFileSync(process.argv[2], "utf8")), process.argv[3], ${JSON.stringify(join(home, "runners"))})));`);
  await writeFile(config, JSON.stringify({ spool_dir: server.bohemia, ado: { author_account: "retained" } }));
  await page.goto(`${server.url}/bohemia/runners/new`);
  const sidebar = page.getByRole("navigation", { name: "Project navigation", exact: true });
  await expect(sidebar.getByRole("button", { name: "Runners", exact: true })).toHaveAttribute("aria-expanded", "true");
  await expect(page.getByRole("button", { name: "Switch project, Bohemia" })).toBeVisible();
  await expect(sidebar.getByRole("link", { name: "Create runner", exact: true })).toHaveAttribute("aria-current", "page");
  await expect(sidebar.getByText("No runners configured", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Runner settings", exact: true }).click();
  await page.getByRole("textbox", { name: "Runner name" }).fill("Book checks");
  await page.getByRole("textbox", { name: "Working directory" }).fill(server.bohemia);
  await page.getByRole("button", { name: "Done", exact: true }).click();
  await page.getByRole("button", { name: "Add first step", exact: true }).click();
  await page.getByRole("button", { name: /On a schedule/ }).click();
  await page.getByRole("button", { name: "Back to canvas", exact: true }).click();
  await page.getByRole("button", { name: "Add step", exact: true }).click();
  await page.getByRole("button", { name: /Run script/ }).click();
  await page.getByRole("textbox", { name: "PowerShell command" }).fill("Write-Output 'isolated fixture'");
  await page.getByRole("button", { name: "Back to canvas", exact: true }).click();
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page).toHaveURL(/\/bohemia\/runners\/runner-[a-z0-9]+$/);
  await expect(sidebar.getByRole("link", { name: "Book checks", exact: true })).toHaveAttribute("aria-current", "page");
  const id = new URL(page.url()).pathname.split("/").at(-1)!;
  const stored = JSON.parse(await readFile(config, "utf8"));
  expect(stored.custom_runners[id].enabled).toBe(false);
  expect(stored.custom_runners[id].nodes[1].command).toContain("isolated fixture");
  expect(stored.ado.author_account).toBe("retained");
  const entry = await readFile(join(home, "runners", id, "run.mjs"), "utf8");
  expect(entry).toContain("runCustom");
  await page.reload();
  await expect(page.getByRole("heading", { name: "Book checks" })).toBeVisible();
  await page.getByRole("button", { name: "Edit On a schedule", exact: true }).click();
  await page.getByRole("spinbutton", { name: "Check every" }).fill("7");
  await page.getByRole("button", { name: "Back to canvas", exact: true }).click();
  const endpoint = `${server.url}/api/projects/bohemia/runners/${id}`;
  const old = await (await page.request.get(endpoint)).json();
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Saved");
  expect((await page.request.put(endpoint, { headers: { Origin: server.url }, data: old })).status()).toBe(409);
  expect((await page.request.put(endpoint, { headers: { Origin: "https://untrusted.example" }, data: old })).status()).toBe(403);
  expect(JSON.parse(await readFile(config, "utf8")).custom_runners[id].intervalSeconds).toBe(420);
  await page.getByRole("button", { name: "Edit On a schedule", exact: true }).click();
  await page.getByRole("radio", { name: "Settings", exact: true }).click();
  await page.getByRole("button", { name: "Change trigger", exact: true }).click();
  await page.getByRole("button", { name: /When a file changes/ }).click();
  await page.getByRole("textbox", { name: "File to watch" }).fill("chapter.md");
  await page.getByRole("button", { name: "Back to canvas", exact: true }).click();
  await page.locator(".react-flow__edge").focus();
  await page.keyboard.press("Enter");
  await page.getByRole("button", { name: "Insert action on connection", exact: true }).click();
  await page.getByRole("button", { name: /^Repository/ }).click();
  await page.getByRole("button", { name: "Back to canvas", exact: true }).click();
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Saved");
  await page.reload();
  await expect(page.getByRole("button", { name: "Edit Repository", exact: true })).toBeVisible();
  const typed = JSON.parse(await readFile(config, "utf8")).custom_runners[id];
  expect(typed.nodes[0].kind).toBe("file-change");
  expect(typed.nodes[0].path).toBe("chapter.md");
  expect(typed.nodes.find((node: { kind: string }) => node.kind === "repository").operation).toBe("refresh");
  const second = await page.request.post(`${server.url}/api/projects/bohemia/runners/second-runner`, {
    headers: { Origin: server.url }, data: { ...old, id: "second-runner", name: "Second runner", revision: undefined },
  });
  expect(second.status()).toBe(201);
  await expect(sidebar.getByRole("link", { name: "Second runner", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Runner settings", exact: true }).click();
  await page.getByRole("textbox", { name: "Runner name" }).fill("Unsaved name");
  await page.getByRole("button", { name: "Done", exact: true }).click();
  await sidebar.getByRole("link", { name: "Second runner", exact: true }).click();
  const guard = page.getByRole("dialog", { name: "Discard unsaved changes?" });
  await expect(guard).toBeVisible();
  await guard.getByRole("button", { name: "Keep editing" }).click();
  await expect(page.getByRole("heading", { name: "Unsaved name", exact: true })).toBeVisible();
  await expect(page).toHaveURL(endpoint.replace("/api/projects", ""));
  await sidebar.getByRole("link", { name: "Second runner", exact: true }).click();
  await guard.getByRole("button", { name: "Discard changes" }).click();
  await expect(page.getByRole("heading", { name: "Second runner", exact: true })).toBeVisible();
  await expect(sidebar.getByRole("link", { name: "Second runner", exact: true })).toHaveAttribute("aria-current", "page");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "Open sidebar" }).click();
  const mobile = page.getByRole("dialog", { name: "Project navigation", exact: true });
  await mobile.getByRole("link", { name: "Book checks", exact: true }).click();
  await expect(mobile).toHaveCount(0);
  await expect(page.getByRole("heading", { name: "Book checks", exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({ width: 1440, height: 900 });
  await writeFile(server.registry, JSON.stringify({ version: 1, projects: [
    { id: "bohemia", name: "Bohemia", root: server.bohemia }, { id: "book-cook", name: "Book Cook", root: server.bookCook },
  ] }));
  await page.reload();
  await page.getByRole("button", { name: "Switch project, Bohemia" }).click();
  await page.getByRole("menuitemradio", { name: "Book Cook", exact: true }).click();
  await expect(page).toHaveURL(`${server.url}/book-cook/runners`);
  await expect(sidebar.getByRole("link", { name: "Book checks", exact: true })).toHaveCount(0);
  await expect(sidebar.getByRole("link", { name: "Second runner", exact: true })).toHaveCount(0);
  await expect(sidebar.getByText("No runners configured", { exact: true })).toBeVisible();
});
