import { test, expect } from "./project-fixture";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type { RunnerWorkflow } from "../src/lib/runner-workflow";

test("existing runner stages and actual prompts load, edit and persist without launching scanners", async ({ page, projectServer: server }) => {
  test.setTimeout(60000);
  const home = join(server.root, "runner-service"), file = join(home, "spool-runners.json");
  await mkdir(join(home, "bridge"), { recursive: true });
  const cli = pathToFileURL(resolve("..", "spool-runners", "bridge", "workflow-cli.mjs")).href;
  const snapshot = pathToFileURL(resolve("..", "spool-runners", "bridge", "runner-snapshot.mjs")).href;
  await writeFile(join(home, "bridge", "workflow-cli.mjs"), `import ${JSON.stringify(cli)};`);
  await writeFile(join(home, "bridge", "runner-snapshot.mjs"), `import { readFileSync } from "node:fs";
    import { runnerSnapshot } from ${JSON.stringify(snapshot)};
    console.log(JSON.stringify(await runnerSnapshot(JSON.parse(readFileSync(process.argv[2], "utf8")), process.argv[3], ${JSON.stringify(join(home, "runners"))})));`);
  await writeFile(file, JSON.stringify({ spool_dir: server.bohemia, ado: { author_account: "fixture@example.invalid", token: "PRIVATE_SENTINEL" },
    pr_reviewer: { enabled: false, workspace_dir: server.bohemia, agent: "reviewer" },
    pr_updater: { enabled: false }, livesite: { enabled: false, workspace_dir: server.bohemia, agent: "engineer" },
    spelling: { enabled: false, workspace_dir: server.bohemia } }));
  await page.goto(`${server.url}/bohemia/runners/pr-reviewer`);
  await expect(page.locator(".react-flow__node")).toHaveCount(3);
  await page.getByRole("button", { name: "Edit Agent", exact: true }).click();
  await page.getByText("Generated event instructions", { exact: true }).click();
  const prompt = page.getByRole("textbox", { name: "Task handoff prompt", exact: true });
  await expect(prompt).toHaveValue(/Source commit: \{\{pr.sourceCommit\}\}/);
  await expect(prompt).toHaveValue(/spool_update_task_status/);
  await expect(prompt).toHaveValue(new RegExp(server.bohemia.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  await page.locator("summary", { hasText: "Agent instructions" }).click();
  await expect(page.getByRole("textbox", { name: "Agent instructions", exact: true })).toHaveValue("# Reviewer\n\nReview carefully.\n");
  await page.getByRole("textbox", { name: "Task instructions", exact: true }).fill("{{event.prompt}}\nInclude the precise regression test.");
  await page.getByRole("button", { name: "Back to canvas" }).click();
  await page.getByRole("button", { name: "Edit Azure DevOps", exact: true }).click();
  await page.getByRole("spinbutton", { name: "Changed revision settle time (seconds)" }).fill("180");
  await page.getByRole("button", { name: "Back to canvas" }).click();
  await page.getByRole("button", { name: "Add step", exact: true }).click();
  await page.getByRole("button", { name: /^Edit data/ }).click();
  await page.getByRole("textbox", { name: "Output JSON" }).fill('{"verification":"precise"}');
  await page.getByRole("button", { name: "Back to canvas" }).click();
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page.getByRole("status")).toHaveText("Saved");
  const stored = JSON.parse(await readFile(file, "utf8"));
  expect(stored.pr_reviewer.enabled).toBe(false);
  expect(stored.pr_reviewer.parameters.revisionSettleSeconds).toBe(180);
  expect(stored.pr_reviewer.workflow.nodes.find((node: { kind: string }) => node.kind === "agent").prompt)
    .toBe("{{event.prompt}}\nInclude the precise regression test.");
  expect(stored.pr_reviewer.workflow.nodes.some((node: { kind: string }) => node.kind === "data")).toBe(true);
  expect(stored.ado.token).toBe("PRIVATE_SENTINEL");
  await page.reload();
  await expect(page.locator(".react-flow__node")).toHaveCount(4);
  await page.getByRole("button", { name: "Edit Agent", exact: true }).click();
  await page.getByText("Generated event instructions", { exact: true }).click();
  await expect(prompt).toHaveValue(/Include the precise regression test/);
  await page.keyboard.press("Escape");
  const endpoint = `${server.url}/api/projects/bohemia/runners/pr-reviewer`;
  const saved: RunnerWorkflow = await (await page.request.get(endpoint)).json();
  expect(JSON.stringify(saved)).not.toContain("PRIVATE_SENTINEL");
  const execution = "123e4567-e89b-42d3-a456-426614174000";
  const records = join(home, "runners", "pr-reviewer", ".runner", "executions");
  await mkdir(records, { recursive: true });
  const record = { id: execution, status: "failed", source: "integration",
    createdAt: new Date().toISOString(), input: {}, steps: [], error: "Fixture event stopped" };
  await writeFile(join(records, `${execution}.json`), JSON.stringify(record));
  await writeFile(join(records, `${execution}.summary.json`), JSON.stringify(record));
  expect((await page.request.get(`${endpoint}/runs`)).status()).toBe(200);
  expect((await page.request.post(`${endpoint}/runs`, { headers: { Origin: server.url }, data: {} })).status()).toBe(400);
  await page.getByRole("radio", { name: "Executions", exact: true }).click();
  await page.getByRole("button", { name: "Refresh executions" }).click();
  await page.getByRole("combobox", { name: "Execution", exact: true }).click();
  await page.getByRole("option", { name: /failed$/ }).click();
  await expect(page.getByText("Fixture event stopped", { exact: true })).toBeVisible();
  await expect(page.getByRole("textbox", { name: "Test input (JSON)" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Execute workflow", exact: true })).toHaveCount(0);
  await page.getByRole("radio", { name: "Editor", exact: true }).click();
  const altered = structuredClone(saved); altered.nodes[0].revisionSettleSeconds = "-3";
  expect((await page.request.put(endpoint, { headers: { Origin: server.url }, data: altered })).status()).toBe(400);
  const truncated = { ...saved, nodes: saved.nodes.slice(0, -1), edges: saved.edges.slice(0, -1) };
  expect((await page.request.put(endpoint, { headers: { Origin: server.url }, data: truncated })).status()).toBe(400);
  const copy = { ...saved, id: "review-copy", name: "Review copy", kind: "custom", revision: "" };
  const created = await page.request.post(`${server.url}/api/projects/bohemia/runners/review-copy`, { headers: { Origin: server.url }, data: copy });
  expect(created.ok()).toBe(true);
  expect((await created.json()).nodes).toEqual(saved.nodes);
  const sidebar = page.getByRole("navigation", { name: "Project navigation" });
  await sidebar.getByRole("link", { name: "pr-updater", exact: true }).click();
  await page.getByRole("button", { name: "Edit Agent", exact: true }).click();
  await page.getByText("Generated event instructions", { exact: true }).click();
  await expect(prompt).toHaveValue(/You are the original implementation owner/);
  await expect(prompt).toHaveValue(/PR_UPDATE_RESULT_FILE/);
  await page.locator("summary", { hasText: "Agent instructions" }).click();
  await expect(page.getByRole("dialog")).toContainText("not the pr-updater agent");
  await page.keyboard.press("Escape");
  await sidebar.getByRole("link", { name: "livesite", exact: true }).click();
  await page.getByRole("button", { name: "Edit Agent", exact: true }).click();
  await page.getByText("Generated event instructions", { exact: true }).click();
  await expect(prompt).toHaveValue(/Livesite incident: \{\{incident.kind\}\}/);
  await expect(prompt).toHaveValue(/The workspace and dependencies are already set up/);
  await page.keyboard.press("Escape");
  await sidebar.getByRole("link", { name: "spelling", exact: true }).click();
  await expect(page.locator(".react-flow__node")).toHaveCount(2);
  await page.getByRole("button", { name: "Edit Repository trigger", exact: true }).click();
  await expect(page.getByRole("spinbutton", { name: "Check every" })).toBeVisible();
});
